"""Prompt template constants for TOEIC Part 3 / Part 4 transcript generation."""

from generator.prompts.templates import (
    DIFFICULTY_BLOCKS,
    PART3_PASSAGE_SPEC_TEMPLATE,
    PART3_ROLE_HEADER,
    PART4_PASSAGE_SPEC_TEMPLATE,
    PART4_ROLE_HEADER,
    PROMPT_TEMPLATE,
    QUESTIONS_BLOCK,
    TRAP_GUIDANCE_BLOCK,
)

__all__ = [
    "DIFFICULTY_BLOCKS",
    "PART3_PASSAGE_SPEC_TEMPLATE",
    "PART3_ROLE_HEADER",
    "PART4_PASSAGE_SPEC_TEMPLATE",
    "PART4_ROLE_HEADER",
    "PROMPT_TEMPLATE",
    "QUESTIONS_BLOCK",
    "TRAP_GUIDANCE_BLOCK",
]
